### ISSUE TITLE
getting errors while running the python program

### ISSUE THREAD

**Issue by hapra** [nassir-malik/IOT-Pi3-Alexa-Automation#8]
this is the error.. Kindly do the needful 

pi@raspberrypi:~/IOT-Pi3-Alexa-Automation-master $ sudo python RPi_name_port_gpio_8_Relays2.py
DEBUG:root:Listening for UPnP broadcasts
DEBUG:root:got local address of 192.168.0.110
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'pc' ready on 192.168.0.110:52004
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'living room' ready on 192.168.0.110:51000
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'room' ready on 192.168.0.110:52002
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'office' ready on 192.168.0.110:53000
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'tv' ready on 192.168.0.110:52003
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'light' ready on 192.168.0.110:52006
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'xbox' ready on 192.168.0.110:52005
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'kitchen' ready on 192.168.0.110:52000
DEBUG:root:Entering fauxmo polling loop
DEBUG:root:Responding to search for pc
Traceback (most recent call last):
  File "RPi_name_port_gpio_8_Relays2.py", line 102, in <module>
    logging.critical("Critical exception: "+ e.args  )
TypeError: cannot concatenate 'str' and 'tuple' objects

**Comment by nassir-malik** [comment]
What version of python you are running?

-Thanks
====================================================
Nassir

**Comment by jbabu** [comment]
use this command                  sudo python3 RPi_name_port_gpio_8_Relays2.py

**Comment by Tommy-Jack** [comment]
Hello Nassir,

i am have the same Problem but i cant found a solution.
I am have Python 2 and 3.

Thanks

**Comment by nassir-malik** [comment]
Can you share the errors- thanks

**Comment by nassir-malik** [comment]
Are you using echo 2nd gen or  plus?

**Comment by User712** [comment]
I am using Amazon Echo Dot 2nd generation

**Comment by sherwood65633** [comment]
Thank you Mr. Nassir for your work. I have having a similar issue with tuple convert error in line 102.the error is as follows:

"Traceback (most recent call last):
 File "RPi_name_port_gpio_8_Relays2.py", line 102, in <module>
    logging.critical("Critical exception: "+ e.args  )
TypeError: Can't convert 'tuple' object to str implicitly"

I have found a message on the boards suggesting changing the GPIO.Output line to"

"GPIO.output(int(11), true) time.sleep(1) GPIO.output(int(11), false)"👍 
but I am getting a syntax error. ( Im sorry, I'm still new to python, but i dont see an error in that line).

could you please assist me with this?

**Comment by sherwood65633** [comment]
Sir, there are two more question I'd like to ask.
- When i run the 8 channel program, it only finds 4. Why?
- I seem to get the prior quested error when I am running discovery, or quiring the "tv" function.
        Again, Thank you so much

**Comment by nassir-malik** [comment]
Are you using python 3?

Send via mobile device

**Comment by nassir-malik** [comment]
Please make sure use python 3.4.4 or above. I have seen this issue when
tried to run it with python 2.7.

-Thanks
====================================================
Nassir

**Comment by sherwood65633** [comment]
I don't know what it is, but it's better and will run consistently for days. Operating relys correctly then throw the same error. 
File "/home/pi/IOT-Pi3-Alexa-Automation-master/fauxmo.py", line 99, in poll
target.do_read(one_ready[0])
File "/home/pi/IOT-Pi3-Alexa-Automation-master/fauxmo.py", line 158, in do_read
data, sender = self.client_sockets[fileno][0].recvfrom(4096)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/IOT-Pi3-Alexa-Automation-master/RPi_name_port_gpio_8_Relays.py", line 101, in
logging.critical("Critical exception: "+ e.args )
TypeError: Can't convert 'tuple' object to str implicitly.
Any more ideas?

**Comment by sherwood65633** [comment]
I don't know what it is, but it's better and will run consistently for days. Operating relys correctly then throw the same error. 
File "/home/pi/IOT-Pi3-Alexa-Automation-master/fauxmo.py", line 99, in poll
target.do_read(one_ready[0])
File "/home/pi/IOT-Pi3-Alexa-Automation-master/fauxmo.py", line 158, in do_read
data, sender = self.client_sockets[fileno][0].recvfrom(4096)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/IOT-Pi3-Alexa-Automation-master/RPi_name_port_gpio_8_Relays.py", line 101, in
logging.critical("Critical exception: "+ e.args )
TypeError: Can't convert 'tuple' object to str implicitly.
Any more ideas?

**Comment by sherwood65633** [comment]
sorry duplicate post.

**Comment by stevenbowyer** [comment]
Try changing 
GPIO.output(int(11), true) time.sleep(1) GPIO.output(int(11), false)

to:
```

if state == 1:
    GPIO.output(11,GPIO.LOW)
else:
    GPIO.output(11,GPIO.HIGH)

```

Worked for me after getting the "TypeError: Can't convert 'tuple' object to str implicitly" error.
Seems something has changed, either amazon side or pi GPIO side?

**Comment by sherwood65633** [comment]
Thank you so much. I'll try this tomorrow

**Comment by stevenbowyer** [comment]
You will need proper indents for the if statement. 

It seems like the code is using the "state" variable directly to set the GPIO to either high or low, but rpi.GPIO doesn't like the value. The if statement bypasses this by setting the GPIO values directly after testing the value of the "state" variable.

**Comment by davidsbright** [comment]
Did it work? i'm having the same issue...
